name: backup-action
jobs:
        backup-nginx:
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v3
                        - run: sh .github/backup.sh
                          
